language: go
env:
  global:
    - CGO_ENABLED=0
    - $BUILD_FLAGS=-ldflags "-X main.version=$VERSION"
script:
  - go test -v
  - VERSION="$(git describe --tags --match v* --always)"
  - echo $VERSION
  - GOOS=linux   GOARCH=386   go build -o bin/modini-386       -ldflags "-X main.version=$VERSION"
  - GOOS=linux   GOARCH=amd64 go build -o bin/modini-amd64     -ldflags "-X main.version=$VERSION"
  - GOOS=linux   GOARCH=arm   go build -o bin/modini-arm       -ldflags "-X main.version=$VERSION"
  - GOOS=linux   GOARCH=arm64 go build -o bin/modini-arm64     -ldflags "-X main.version=$VERSION"
  - GOOS=darwin  GOARCH=amd64 go build -o bin/modini-darwin    -ldflags "-X main.version=$VERSION"
  - GOOS=windows GOARCH=386   go build -o bin/modini.exe       -ldflags "-X main.version=$VERSION"
  - GOOS=windows GOARCH=amd64 go build -o bin/modini-amd64.exe -ldflags "-X main.version=$VERSION"
  - cd bin
  - sha256sum modini* | tee SHA256SUMS
  - file modini*
  - ls -l --human-readable
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Uwr+N+XkEQbep6qozYbauCrATMyxWQ/+5H6xZR45bSQNCmBBsU9NZp7ZyMdwA8YTPbGvGrfakScD/VOqeN7QcEVDyP3xhbMCvF0uji2+YBNDWfYVeqgmvwJx4cHhdBTIm96cSm8xMTGciCRMQAcYaUK/ZuEbD1pC2BaduqsHC+I5y6JTga8FpaA4B8ETSuZDHqxUVBfRmNPa0awm52oG3sMnvdV4wOuJcsNYNcWWIbmvpYm27md4dBipaxciu9AMqMWHlZqwLb+kdY6YA7Yxv+shoQqO/H9/WaHtf+CHisjFTwt646ex5U6owH/VSu6sDMa89EDavg64lZGn1B0W5he8KQt0mthL0WAIb7lMt0NDL75JY8mMilFp59GO6DU5WQ7w8ZUsSGgWFb6A22rKeDx3Jn2625WXJ+qvcStG6MlonCC2z8yDbSWiK/BBhGtXGOOt5eCLq3iS07JLogV7iTrZ2gp4WbXknYMfsxZcB6dS1gdzYTdroz0kVms46kbQj2hz95VfUDdoXt9jpqU7s4WxzXnM44xUTnxzlm7QomEZLdByqJErAQvkPmuRbdqYxeSAD/TQRA0F5X0hCEn8bSAHEaT9fzOjtahcJ7y2TIGS7aYZMqHyr17OYb3/oz4/7fnZrqV27SoTsCjAbK5uAnQeho+3bqXyqWZjgbqMjxI=
  file:
    - bin/modini-386
    - bin/modini-amd64
    - bin/modini-arm
    - bin/modini-arm64
    - bin/modini-darwin
    - bin/modini.exe
    - bin/modini-amd64.exe
    - bin/SHA256SUMS
  on:
    tags: true
